repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.27
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: generate-docstrings-from-tests
        name: generate docstrings from tests
        entry: uv run -m scripts.generate_docstrings_from_tests
        language: python
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
  - repo: local
    hooks:
      - id: repo-map
        name: repo_map
        entry: uv run -m repo_mapper
        language: python
        pass_filenames: false
        args:
          - --repo-root
          - .
          - --readme-path
          - ./README.md
          - --gitignore-path
          - ./.gitignore
          - --allowed-exts
          - py,md,yaml,toml,lock
          - --ignore-dirs
          - .venv,target,.git,mock_data,.pytest_cache
          # - --ignore-hidden
      - id: pytest
        name: pytest
        entry: uv run pytest -vv --cov=src --cov-report term-missing:skip-covered --cov-report=json:coverage.json
        language: python
        pass_filenames: false
        always_run: true
